---
- project:
    templates:
      - build-openstack-docs-pti
    check:
      jobs:
        - build-openstack-releasenotes
        - openstack-tox-linters
    gate:
      jobs:
        - build-openstack-releasenotes
        - openstack-tox-linters
    post:
      jobs:
        - publish-stx-tox
        - publish-stx-releasenotes
